version: "3.9"

services:
#  app:
#    build:
#      context: .
#      dockerfile: "Dockerfile"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: