import Navbar from "@/components/navbar";
import Head from "next/head";

export default function Layout({children}) {
    return (
        <>
            <Head>
                <title>Empulse - Assignment</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar></Navbar>
            <main style={{padding: "16px"}}>
                {children}
            </main>
        </>
    );
}