import {useEffect} from "react";
import {useRouter} from 'next/router'
import Navbar from "@/components/navbar";
import Head from "next/head";

export default function Layout({children}) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar></Navbar>
            <main>
                {children}
            </main>
        </>
    );
}